build.output_basename=beerday
build.product_name=Happy Beerday
build.product_identifier=cz.4sensegaming.beerday
build.product_version=0.9.5
build.product_version_semantic=0.9.5
build.windows_bundle=2
build.linux_bundle=2
build.mac_bundle=2